name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: install dependecies
        run: npm install

      - name: Build
        run: npm start &


      - name: 🚮 Remove former files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.PRIVATE_KEY}}
          port: ${{secrets.PORT}}
          script: |
            sudo rm -rf ./recipe-project 

      - name: 📂 Copy file via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.PRIVATE_KEY}}
          port: ${{secrets.PORT}}
          source: "./*"
          target: .

      - name: 🫡 Run deploy script on remote
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST }}
          username: ${{secrets.USER }}
          key: ${{secrets.PRIVATE_KEY }}
          port: ${{secrets.PORT }}
          script: |
            PID=$(pgrep -f "node index.js")
            if [ -n "$PID" ]; then
              echo $PID;
              pkill $PID;
              echo "Deleted process" 
            else 
              echo "Nothing to delete";
            fi 
            npm install 
            nohup npm start &